name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    name: Node ${{ matrix.node-version }}

    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Install lerna
      run: npm install --global lerna@3

    - name: Bootstrap dependencies in packages
      run: lerna bootstrap

    - name: Build packages
      run: lerna run build

    - name: Run tests
      run: npm test
      env:
        CI: true
